Fixed regex to work with OPNsense 21.x msg format
IRQ10/Graylog-OPNsense_Extractors pull request #5
Opened 2021-02-07 15:36 UTC by knipp

Hi, as people have already noticed in the Issues, the regex for the OPNsense extractors doesn't work anymore due to a change in the filterlog messages. My fix basically ignores the recently introduced field in angled brackets.
I tested this against the most recent versions of Graylog (4.0.1) and OPNsense (21.1)

2021-03-22 17:17 UTC, elevul commented
I'm having the same error with your code:

![image](https://user-images.githubusercontent.com/6944931/112030710-d1d9ad80-8b3a-11eb-992c-3d65a9c75e0c.png)

2021-03-23 19:56 UTC, knipp commented
Hi, the .json is not in the format of a content pack, you have to import it differently. 

Try navigating to System / Inputs, and "Manage Extractors" for the Syslog input where your receive the OPNsense messages. There, with "Actions / Import extractors", you can just copy/paste the json content and it should create all the defined extractors for you.

2021-06-17 19:36 UTC, Alphakilo commented
Hey @knipp! Are you still actively using the extractors?

Seems like @IRQ10 is AWOL. There was another breaking change in the log format, so I decided to [fork the project](https://github.com/Alphakilo/Graylog-OPNsense_Extractors) and incorporated your PR.

2021-06-17 19:45 UTC, knipp commented
Hey, thanks for letting me know! I was using it for a small poc at home and didn't touch it in a while. Glad the (mini) change is of use!
________________________________
From: Niklas ***@***.***>
Sent: Thursday, June 17, 2021 9:36:52 PM
To: IRQ10/Graylog-OPNsense_Extractors ***@***.***>
Cc: knipp ***@***.***>; Mention ***@***.***>
Subject: Re: [IRQ10/Graylog-OPNsense_Extractors] Fixed regex to work with OPNsense 21.x msg format (#5)


Hey @knipp<https://github.com/knipp>! Are you still actively using the extractors?

Seems like @IRQ10<https://github.com/IRQ10> is AWOL. There was another breaking change in the log format, so I decided to fork the project<https://github.com/Alphakilo/Graylog-OPNsense_Extractors> and incorporated your PR.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/IRQ10/Graylog-OPNsense_Extractors/pull/5#issuecomment-863511211>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AF6MXTW7TQPYXJB7YMDLIQLTTJFFJANCNFSM4XHR5FRA>.

2021-06-18 13:02 UTC, irq10-holding commented
I haven't used this in some time and appreciate you picking up the project @Alphakilo .

2021-06-26 22:54 UTC, irq10-holding requested changes
I updated my rules to be more consistent and address the new OPNsense message format.

2021-06-27 14:03 UTC, IRQ10 reviewed
6/27/21 - I have updated my extractors to work with the new format.

2021-06-27 14:09 UTC, closed without merging